package com.upg.ucars.mapping.framework.bpm;

import java.util.Date;

/**
 * ProcessDef generated by MyEclipse Persistence Tools
 */

public class ProcessDef implements java.io.Serializable {

	// Fields

	private Long id;
	private String procName;
	private String procNameKey;//如procName=loan_001,则procNameKey=loan.
	private String procCnName;
	private String status;
	private String desiProdNo;
	private Date createTime;
	private Long jbpmPdId;
	/*
	 * 版本号
	 */
	private Integer version;

	// Constructors

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	/** default constructor */
	public ProcessDef() {
	}

	/** minimal constructor */
	public ProcessDef(String procName) {
		this.procName = procName;
	}

	/** full constructor */
	public ProcessDef(String procName, String procCnName, String status,
			String desiProdNo, Integer version) {
		this.procName = procName;
		this.procCnName = procCnName;
		this.status = status;
		this.desiProdNo = desiProdNo;
		this.version = version;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getProcName() {
		return this.procName;
	}

	public void setProcName(String procName) {
		this.procName = procName;
	}

	public String getProcCnName() {
		return this.procCnName;
	}

	public void setProcCnName(String procCnName) {
		this.procCnName = procCnName;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDesiProdNo() {
		return this.desiProdNo;
	}

	public void setDesiProdNo(String desiProdNo) {
		this.desiProdNo = desiProdNo;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProcessDef other = (ProcessDef) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	public Long getJbpmPdId() {
		return jbpmPdId;
	}

	public void setJbpmPdId(Long jbpmPdId) {
		this.jbpmPdId = jbpmPdId;
	}

	public String getProcNameKey() {
		return procNameKey;
	}

	public void setProcNameKey(String procNameKey) {
		this.procNameKey = procNameKey;
	}

}