package com.upg.cfsettle.mapping.organization;
// Generated 2017-3-28 14:26:51 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * CfsOrgArea generated by hbm2java
 */
public class CfsOrgArea implements java.io.Serializable {

	private Long id;
	private String areaName;
	private String overRange;
	private Byte status;
	private Long csysid;
	private Date ctime;
	private Long msysid;
	private Date mtime;

	public CfsOrgArea() {
	}
	
	public CfsOrgArea(Byte status) {
		this.status = status;
	}

	public CfsOrgArea(Long id, String areaName, String overRange, Byte status, Long csysid, Date ctime, Long msysid, Date mtime) {
		this.id = id;
		this.areaName = areaName;
		this.overRange = overRange;
		this.status = status;
		this.csysid = csysid;
		this.ctime = ctime;
		this.msysid = msysid;
		this.mtime = mtime;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public String getOverRange() {
		return this.overRange;
	}

	public void setOverRange(String overRange) {
		this.overRange = overRange;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Long getCsysid() {
		return csysid;
	}

	public void setCsysid(Long csysid) {
		this.csysid = csysid;
	}

	public Date getCtime() {
		return ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Long getMsysid() {
		return msysid;
	}

	public void setMsysid(Long msysid) {
		this.msysid = msysid;
	}

	public Date getMtime() {
		return mtime;
	}

	public void setMtime(Date mtime) {
		this.mtime = mtime;
	}
}
