package com.upg.cfsettle.mapping.prj;
// Generated 2017-3-30 10:19:12 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * CfsPrj generated by hbm2java
 */
public class CfsPrj implements java.io.Serializable {

	/**
	 * TODO（用一句话描述这个变量表示什么）
	 */
	private static final long serialVersionUID = -5815690143864034500L;
	private Long id;
	private String prjName;
	private String prjUseName;
	private String prjMobile;
	private BigDecimal demandAmount;
	private BigDecimal remainingAmount;
	private BigDecimal yearRate;
	private Integer timeLimit;
	private String timeLimitUnit;
	private Integer timeLimitDay;
	private BigDecimal periodRate;
	private Byte status;
	private String repayWay;
	private Date startBidTime;
	private Date endBidTime;
	private Date lastRepayTime;
	private BigDecimal minLoanAmount;
	private Date loanTime;
	private BigDecimal totalRate;
	private BigDecimal areaRate;
	private BigDecimal deptRate;
	private BigDecimal teamRate;
	private BigDecimal sysuserRate;
	private String remark;
	private Long csysid;
	private Date ctime;
	private Long msysid;
	private Date mtime;

	public CfsPrj() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPrjName() {
		return prjName;
	}

	public void setPrjName(String prjName) {
		this.prjName = prjName;
	}

	public BigDecimal getDemandAmount() {
		return demandAmount;
	}

	public void setDemandAmount(BigDecimal demandAmount) {
		this.demandAmount = demandAmount;
	}

	public BigDecimal getRemainingAmount() {
		return remainingAmount;
	}

	public void setRemainingAmount(BigDecimal remainingAmount) {
		this.remainingAmount = remainingAmount;
	}

	public Integer getTimeLimit() {
		return timeLimit;
	}

	public void setTimeLimit(Integer timeLimit) {
		this.timeLimit = timeLimit;
	}

	public String getTimeLimitUnit() {
		return timeLimitUnit;
	}

	public void setTimeLimitUnit(String timeLimitUnit) {
		this.timeLimitUnit = timeLimitUnit;
	}

	public Integer getTimeLimitDay() {
		return timeLimitDay;
	}

	public void setTimeLimitDay(Integer timeLimitDay) {
		this.timeLimitDay = timeLimitDay;
	}

	public BigDecimal getPeriodRate() {
		return periodRate;
	}

	public void setPeriodRate(BigDecimal periodRate) {
		this.periodRate = periodRate;
	}

	public Byte getStatus() {
		return status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public String getRepayWay() {
		return repayWay;
	}

	public void setRepayWay(String repayWay) {
		this.repayWay = repayWay;
	}

	public Date getStartBidTime() {
		return startBidTime;
	}

	public void setStartBidTime(Date startBidTime) {
		this.startBidTime = startBidTime;
	}

	public Date getEndBidTime() {
		return endBidTime;
	}

	public void setEndBidTime(Date endBidTime) {
		this.endBidTime = endBidTime;
	}

	public Date getLastRepayTime() {
		return lastRepayTime;
	}

	public void setLastRepayTime(Date lastRepayTime) {
		this.lastRepayTime = lastRepayTime;
	}

	public BigDecimal getMinLoanAmount() {
		return minLoanAmount;
	}

	public void setMinLoanAmount(BigDecimal minLoanAmount) {
		this.minLoanAmount = minLoanAmount;
	}

	public Date getLoanTime() {
		return loanTime;
	}

	public void setLoanTime(Date loanTime) {
		this.loanTime = loanTime;
	}

	public BigDecimal getTotalRate() {
		return totalRate;
	}

	public void setTotalRate(BigDecimal totalRate) {
		this.totalRate = totalRate;
	}

	public BigDecimal getAreaRate() {
		return areaRate;
	}

	public void setAreaRate(BigDecimal areaRate) {
		this.areaRate = areaRate;
	}

	public BigDecimal getDeptRate() {
		return deptRate;
	}

	public void setDeptRate(BigDecimal deptRate) {
		this.deptRate = deptRate;
	}

	public BigDecimal getTeamRate() {
		return teamRate;
	}

	public void setTeamRate(BigDecimal teamRate) {
		this.teamRate = teamRate;
	}

	public BigDecimal getSysuserRate() {
		return sysuserRate;
	}

	public void setSysuserRate(BigDecimal sysuserRate) {
		this.sysuserRate = sysuserRate;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Long getCsysid() {
		return csysid;
	}

	public void setCsysid(Long csysid) {
		this.csysid = csysid;
	}

	public Date getCtime() {
		return ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Long getMsysid() {
		return msysid;
	}

	public void setMsysid(Long msysid) {
		this.msysid = msysid;
	}

	public Date getMtime() {
		return mtime;
	}

	public void setMtime(Date mtime) {
		this.mtime = mtime;
	}

	public String getPrjUseName() {
		return prjUseName;
	}

	public void setPrjUseName(String prjUseName) {
		this.prjUseName = prjUseName;
	}

	public String getPrjMobile() {
		return prjMobile;
	}

	public void setPrjMobile(String prjMobile) {
		this.prjMobile = prjMobile;
	}

	public BigDecimal getYearRate() {
		return yearRate;
	}

	public void setYearRate(BigDecimal yearRate) {
		this.yearRate = yearRate;
	}
}
