package com.upg.cfsettle.mapping.prj;
// Generated 2017-3-30 10:19:46 by Hibernate Tools 5.2.1.Final

/**
 * CfsPrjExt generated by hbm2java
 */
public class CfsPrjExt implements java.io.Serializable {

	/**
	 * TODO（用一句话描述这个变量表示什么）
	 */
	private static final long serialVersionUID = -7501439986133242569L;
	private int prjId;
	private String tenantName;
	private String tenantBank;
	private Integer provinceId;
	private Integer cityId;
	private Integer subBank;
	private String accountNo;
	private Integer contractAttid;
	private Integer periodAttid;
	private Integer guaranteAttid;
	private Integer spreadAttid;
	private Integer csysid;
	private Integer ctime;
	private Integer msysid;
	private Integer mtime;

	public CfsPrjExt() {
	}

	public CfsPrjExt(int prjId) {
		this.prjId = prjId;
	}

	public CfsPrjExt(int prjId, String tenantName, String tenantBank, Integer provinceId, Integer cityId,
			Integer subBank, String accountNo, Integer contractAttid, Integer periodAttid, Integer guaranteAttid,
			Integer spreadAttid, Integer csysid, Integer ctime, Integer msysid, Integer mtime) {
		this.prjId = prjId;
		this.tenantName = tenantName;
		this.tenantBank = tenantBank;
		this.provinceId = provinceId;
		this.cityId = cityId;
		this.subBank = subBank;
		this.accountNo = accountNo;
		this.contractAttid = contractAttid;
		this.periodAttid = periodAttid;
		this.guaranteAttid = guaranteAttid;
		this.spreadAttid = spreadAttid;
		this.csysid = csysid;
		this.ctime = ctime;
		this.msysid = msysid;
		this.mtime = mtime;
	}

	public int getPrjId() {
		return this.prjId;
	}

	public void setPrjId(int prjId) {
		this.prjId = prjId;
	}

	public String getTenantName() {
		return this.tenantName;
	}

	public void setTenantName(String tenantName) {
		this.tenantName = tenantName;
	}

	public String getTenantBank() {
		return this.tenantBank;
	}

	public void setTenantBank(String tenantBank) {
		this.tenantBank = tenantBank;
	}

	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getSubBank() {
		return this.subBank;
	}

	public void setSubBank(Integer subBank) {
		this.subBank = subBank;
	}

	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public Integer getContractAttid() {
		return this.contractAttid;
	}

	public void setContractAttid(Integer contractAttid) {
		this.contractAttid = contractAttid;
	}

	public Integer getPeriodAttid() {
		return this.periodAttid;
	}

	public void setPeriodAttid(Integer periodAttid) {
		this.periodAttid = periodAttid;
	}

	public Integer getGuaranteAttid() {
		return this.guaranteAttid;
	}

	public void setGuaranteAttid(Integer guaranteAttid) {
		this.guaranteAttid = guaranteAttid;
	}

	public Integer getSpreadAttid() {
		return this.spreadAttid;
	}

	public void setSpreadAttid(Integer spreadAttid) {
		this.spreadAttid = spreadAttid;
	}

	public Integer getCsysid() {
		return this.csysid;
	}

	public void setCsysid(Integer csysid) {
		this.csysid = csysid;
	}

	public Integer getCtime() {
		return this.ctime;
	}

	public void setCtime(Integer ctime) {
		this.ctime = ctime;
	}

	public Integer getMsysid() {
		return this.msysid;
	}

	public void setMsysid(Integer msysid) {
		this.msysid = msysid;
	}

	public Integer getMtime() {
		return this.mtime;
	}

	public void setMtime(Integer mtime) {
		this.mtime = mtime;
	}

}
