package com.upg.cfsettle.mapping.prj;
// Generated 2017-3-30 10:19:46 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * CfsPrjExt generated by hbm2java
 */
public class CfsPrjExt implements java.io.Serializable {


	/**
	 * TODO（用一句话描述这个变量表示什么）
	 */
	private static final long serialVersionUID = 6494921747164316960L;
	private Long prjId;
	private String tenantName;
	private String tenantBank;
	private Integer provinceId;
	private Integer cityId;
	private String subBank;
	private String accountNo;
	private Long contractAttid;
	private Long periodAttid;
	private Long guaranteAttid;
	private Long spreadAttid;
	private Long csysid;
	private Date ctime;
	private Long msysid;
	private Date mtime;

	private String contractName;
	private String periodName;
	private String guaranteName;
	private String spreadName;

	public CfsPrjExt() {
	}

	public String getContractName() {
		return contractName;
	}

	public void setContractName(String contractName) {
		this.contractName = contractName;
	}

	public String getPeriodName() {
		return periodName;
	}

	public void setPeriodName(String periodName) {
		this.periodName = periodName;
	}

	public String getGuaranteName() {
		return guaranteName;
	}

	public void setGuaranteName(String guaranteName) {
		this.guaranteName = guaranteName;
	}

	public String getSpreadName() {
		return spreadName;
	}

	public void setSpreadName(String spreadName) {
		this.spreadName = spreadName;
	}

	public Long getPrjId() {
		return prjId;
	}

	public void setPrjId(Long prjId) {
		this.prjId = prjId;
	}

	public String getTenantName() {
		return tenantName;
	}

	public void setTenantName(String tenantName) {
		this.tenantName = tenantName;
	}

	public String getTenantBank() {
		return tenantBank;
	}

	public void setTenantBank(String tenantBank) {
		this.tenantBank = tenantBank;
	}

	public Integer getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public String getSubBank() {
		return subBank;
	}

	public void setSubBank(String subBank) {
		this.subBank = subBank;
	}

	public String getAccountNo() {
		return accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public Long getContractAttid() {
		return contractAttid;
	}

	public void setContractAttid(Long contractAttid) {
		this.contractAttid = contractAttid;
	}

	public Long getPeriodAttid() {
		return periodAttid;
	}

	public void setPeriodAttid(Long periodAttid) {
		this.periodAttid = periodAttid;
	}

	public Long getGuaranteAttid() {
		return guaranteAttid;
	}

	public void setGuaranteAttid(Long guaranteAttid) {
		this.guaranteAttid = guaranteAttid;
	}

	public Long getSpreadAttid() {
		return spreadAttid;
	}

	public void setSpreadAttid(Long spreadAttid) {
		this.spreadAttid = spreadAttid;
	}

	public Long getCsysid() {
		return csysid;
	}

	public void setCsysid(Long csysid) {
		this.csysid = csysid;
	}

	public Date getCtime() {
		return ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Long getMsysid() {
		return msysid;
	}

	public void setMsysid(Long msysid) {
		this.msysid = msysid;
	}

	public Date getMtime() {
		return mtime;
	}

	public void setMtime(Date mtime) {
		this.mtime = mtime;
	}
}
